---
logging:
  level: INFO
  loggers:
    com.rupesh.ems: DEBUG
database:
  driverClass: org.postgresql.Driver

  user: postgres
  password: postgres

  url: jdbc:postgresql://localhost:5433/ems

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true
    hibernate.format_sql: true
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"

  minSize: 8
  maxSize: 32

jwt:
  secret: "super-secret-key"
  expireInMilliSec: 3600000

bootstrapadmin:
  enabled: true
  name: "admin"
  email: "admin@ems.com"
  phone: "123"
  password: "super-secret"

emailservice:
  username: "admin@ems.com"
  password: "ems123@"

razorpay:
  keyId: "rzp_test_YOUR_KEY_ID"
  keySecret: "YOUR_KEY_SECRET"
